const state={view:'dashboard',leads:[]};
const stages=['线索接入','现场测绘','方案出图','算量报价','商务谈判'];
const $=s=>document.querySelector(s);const money=n=>'¥ '+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2});
function toast(text){const e=$('#toast');e.textContent=text;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2200)}
function stageHtml(current){return `<div class="stage">${stages.map((s,i)=>`<span class="${i<current?'done':i===current?'current':''}">${i<current?'✓ ':''}${s}</span>`).join('')}</div>`}
function layout(content){$('#view').innerHTML=content}
function dashboard(){layout(`<div class="grid stat-grid"><div class="stat"><span class="glyph">◎</span><span class="label">本月新增线索</span><strong>12</strong><span class="delta">↑ 较上月 +20%</span></div><div class="stat"><span class="glyph">▣</span><span class="label">进行中项目</span><strong>8</strong><span class="delta">其中 2 个需重点关注</span></div><div class="stat"><span class="glyph">✓</span><span class="label">待处理工单</span><strong>3</strong><span class="delta">2 项即将超时</span></div><div class="stat"><span class="glyph">¥</span><span class="label">本月已回款</span><strong>¥ 468,000</strong><span class="delta">完成目标 62%</span></div></div><div class="section-head"><h2>项目进度与风险</h2><button class="link" data-go="projects">查看全部项目 →</button></div><div class="card table-wrap"><table><thead><tr><th>项目</th><th>项目经理</th><th>当前进度</th><th>合同竣工日</th><th>风险状态</th></tr></thead><tbody><tr><td><span class="project-name">星河科技办公楼改造</span><span class="sub">XM-2607-0001</span></td><td>刘工</td><td><div class="progress"><i style="width:62%"></i></div><span class="sub">62%</span></td><td>2026-08-30</td><td><span class="badge orange">工期预警 · 12 天</span></td></tr><tr><td><span class="project-name">远航律所办公室修缮</span><span class="sub">XM-2607-0002</span></td><td>张工</td><td><div class="progress"><i style="width:38%"></i></div><span class="sub">38%</span></td><td>2026-09-18</td><td><span class="badge green">正常</span></td></tr><tr><td><span class="project-name">南山咖啡旗舰店</span><span class="sub">XM-2606-0012</span></td><td>刘工</td><td><div class="progress"><i style="width:86%;background:#d97706"></i></div><span class="sub">86%</span></td><td>2026-07-16</td><td><span class="badge red">关键路径延误</span></td></tr></tbody></table></div><div class="grid split"><div><div class="section-head"><h2>待办事项</h2><button class="link">查看全部 →</button></div><div class="card timeline"><div class="timeline-item"><i class="dot"></i><div><strong>审批赢单：星河科技办公楼改造</strong><p>合同预估 ¥1,280,000，超过审批阈值 · 陈晓提交</p></div></div><div class="timeline-item"><i class="dot" style="background:#d97706"></i><div><strong>2 项整改工单待验收</strong><p>星河科技办公楼改造 · 待验收超过 20 小时</p></div></div><div class="timeline-item"><i class="dot" style="background:#dc2626"></i><div><strong>远航律所首期款已逾期 8 天</strong><p>应收 ¥96,000 · 请跟进确认</p></div></div></div></div><div><div class="section-head"><h2>重点风险</h2><button class="link" data-go="contracts">查看详情 →</button></div><div class="card risk-list"><div class="risk"><i class="risk-icon">!</i><div><strong>南山咖啡旗舰店</strong><small>关键路径任务延误 3 天</small></div></div><div class="risk"><i class="risk-icon">¥</i><div><strong>远航律所办公室修缮</strong><small>首期付款逾期超过 7 天</small></div></div><div class="risk"><i class="risk-icon">✓</i><div><strong>星河科技办公楼改造</strong><small>存在 2 项未闭环整改工单</small></div></div></div></div></div>`) }
function leads(){layout(`<div class="toolbar"><div class="filters"><input class="input" id="lead-search" placeholder="搜索线索名称、客户" /><select id="stage-filter"><option value="">全部阶段</option>${stages.map(s=>`<option>${s}</option>`).join('')}</select></div><button class="primary" id="add-lead">＋ 新建线索</button></div><div class="card table-wrap"><table><thead><tr><th>线索名称</th><th>客户</th><th>面积 / 预算</th><th>当前阶段</th><th>负责人</th><th>阶段停留</th><th>操作</th></tr></thead><tbody id="lead-body"></tbody></table></div>`);renderLeadRows();$('#add-lead').onclick=openLeadModal;$('#lead-search').oninput=renderLeadRows;$('#stage-filter').onchange=renderLeadRows}
function renderLeadRows(){const q=($('#lead-search')?.value||'').trim();const f=$('#stage-filter')?.value||'';const rows=state.leads.filter(x=>(!q||x.name.includes(q)||x.customer.includes(q))&&(!f||stages[x.stage]===f));$('#lead-body').innerHTML=rows.map((x,index)=>`<tr><td><span class="project-name">${x.name}</span></td><td>${x.customer}</td><td>${x.area}<span class="sub">${x.budget}</span></td><td>${stageHtml(x.stage)}</td><td>${x.owner}</td><td><span class="${x.age.includes('6')?'badge orange':''}">${x.age}</span></td><td><button class="action" data-advance="${index}">推进阶段</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无符合条件的线索</td></tr>';document.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>{const lead=rows[Number(b.dataset.advance)];if(lead.stage<4){lead.stage++;lead.age=`${stages[lead.stage]}第 0 天`;renderLeadRows();toast('已推进至 '+stages[lead.stage])}else{toast('请在详情中选择赢单或输单')}})}
function projects(){layout(`<div class="notice">星河科技办公楼改造存在未闭环整改工单，隐蔽工程验收与竣工验收已锁定。</div><div class="card table-wrap"><table><thead><tr><th>项目编号</th><th>项目名称</th><th>业务负责人</th><th>项目经理</th><th>合同金额</th><th>进度</th><th>状态</th></tr></thead><tbody><tr><td>XM-2607-0001</td><td><span class="project-name">星河科技办公楼改造</span><span class="sub">大型项目 · BOM V1.0 已确认</span></td><td>陈晓</td><td>刘工</td><td>¥ 1,280,000</td><td><div class="progress"><i style="width:62%"></i></div><span class="sub">62%</span></td><td><span class="badge orange">工期预警</span></td></tr><tr><td>XM-2607-0002</td><td><span class="project-name">远航律所办公室修缮</span><span class="sub">大型项目 · BOM V0.1 草稿</span></td><td>李敏</td><td>张工</td><td>¥ 320,000</td><td><div class="progress"><i style="width:38%"></i></div><span class="sub">38%</span></td><td><span class="badge green">施工中</span></td></tr><tr><td>XM-2606-0012</td><td><span class="project-name">南山咖啡旗舰店</span><span class="sub">大型项目 · BOM V1.2 已变更</span></td><td>陈晓</td><td>刘工</td><td>¥ 486,000</td><td><div class="progress"><i style="width:86%;background:#d97706"></i></div><span class="sub">86%</span></td><td><span class="badge red">逾期风险</span></td></tr></tbody></table></div>`) }
function bom(){layout(`<div class="card bom-summary"><div><h3>星河科技办公楼改造 · BOM 台账</h3><p>BOM- XM-2607-0001 · V1.0 已确认 · 2026-07-04 由刘工确认</p></div><div class="segmented"><button class="active">V1.0</button><button>V0.1</button><button class="primary" id="new-bom">＋ 创建变更版本</button></div></div><div class="grid kpi-grid" style="margin-top:18px"><div class="card kpi"><p>BOM 预估成本</p><strong>¥ 645,280</strong></div><div class="card kpi"><p>已确认采购订单</p><strong>¥ 402,600</strong></div><div class="card kpi"><p>采购完成率</p><strong>62.4%</strong></div></div><div class="card table-wrap"><table><thead><tr><th>物料编码</th><th>物料名称 / 规格</th><th>设计用量</th><th>损耗率</th><th>采购数量</th><th>单价</th><th>小计</th></tr></thead><tbody><tr><td>MT-0012</td><td>石膏板<span class="sub">12mm 防潮型 / 张</span></td><td>680</td><td>5%</td><td>714</td><td>¥ 48.00</td><td>¥ 34,272.00</td></tr><tr><td>MT-0048</td><td>矿棉吸音板<span class="sub">600×600mm / ㎡</span></td><td>520</td><td>3%</td><td>536</td><td>¥ 86.00</td><td>¥ 46,096.00</td></tr><tr><td>MT-0066</td><td>LED 平板灯<span class="sub">600×600mm / 套</span></td><td>96</td><td>2%</td><td>98</td><td>¥ 138.00</td><td>¥ 13,524.00</td></tr><tr><td>MT-0108</td><td>地毯<span class="sub">PVC 方块地毯 / ㎡</span></td><td>730</td><td>5%</td><td>767</td><td>¥ 112.00</td><td>¥ 85,904.00</td></tr></tbody></table></div>`);$('#new-bom').onclick=()=>toast('已创建 V1.1 草稿版本，请维护变更明细')}
function workorders(){layout(`<div class="toolbar"><div class="filters"><select><option>全部状态</option><option>待派发</option><option>处理中</option><option>待验收</option></select><select><option>全部项目</option><option>星河科技办公楼改造</option></select></div><button class="primary" id="add-work">＋ 拍照建单</button></div><div class="card table-wrap"><table><thead><tr><th>工单编号</th><th>问题描述</th><th>项目</th><th>责任人</th><th>状态</th><th>剩余时间</th><th>操作</th></tr></thead><tbody><tr><td>WO-2607-0038</td><td><span class="project-name">西侧卫生间防水渗漏</span><span class="sub">整改类 · 已上传 3 张现场照片</span></td><td>星河科技办公楼改造</td><td>刘工</td><td><span class="badge orange">待验收</span></td><td class="red">已超时 2 小时</td><td><button class="action" data-close-work>验收销账</button></td></tr><tr><td>WO-2607-0039</td><td><span class="project-name">走廊吊顶收口不平整</span><span class="sub">整改类 · 已上传 2 张现场照片</span></td><td>星河科技办公楼改造</td><td>李工</td><td><span class="badge blue">处理中</span></td><td>剩余 26 小时</td><td><button class="action">查看</button></td></tr><tr><td>WO-2607-0042</td><td><span class="project-name">会议室插座位置调整</span><span class="sub">一般工单</span></td><td>远航律所办公室修缮</td><td>张工</td><td><span class="badge blue">待派发</span></td><td>剩余 18 小时</td><td><button class="action">派发</button></td></tr></tbody></table></div>`);$('[data-close-work]').onclick=()=>openWorkModal()}
function labor(){layout(`<div class="toolbar"><div class="filters"><input class="input" value="2026-07-11" type="date" /><select><option>全部项目</option></select></div><button class="primary" id="add-labor">＋ 填报日报</button></div><div class="grid kpi-grid"><div class="card kpi"><p>今日出勤人数</p><strong>36 人</strong></div><div class="card kpi"><p>今日人工成本</p><strong>¥ 9,840</strong></div><div class="card kpi"><p>待审核日报</p><strong>2 条</strong></div></div><div class="card table-wrap"><table><thead><tr><th>项目</th><th>日期</th><th>工种</th><th>出勤人数</th><th>工时</th><th>人工成本</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>星河科技办公楼改造</td><td>2026-07-11</td><td>水电</td><td>8 人</td><td>8 h</td><td>¥ 2,560</td><td><span class="badge orange">待审核</span></td><td><button class="action" data-approve>审核通过</button></td></tr><tr><td>星河科技办公楼改造</td><td>2026-07-11</td><td>木工</td><td>12 人</td><td>8 h</td><td>¥ 3,840</td><td><span class="badge green">已审核</span></td><td><button class="action">查看</button></td></tr><tr><td>远航律所办公室修缮</td><td>2026-07-11</td><td>瓦工</td><td>6 人</td><td>8 h</td><td>¥ 1,920</td><td><span class="badge green">已审核</span></td><td><button class="action">查看</button></td></tr></tbody></table></div>`);$('[data-approve]').onclick=e=>{e.target.closest('tr').children[6].innerHTML='<span class="badge green">已审核</span>';e.target.textContent='查看';toast('日报已审核，人工成本已计入利润看板')}}
function contracts(){layout(`<div class="grid kpi-grid"><div class="card kpi"><p>合同动态总额</p><strong>¥ 2,086,000</strong></div><div class="card kpi"><p>本月应收款</p><strong>¥ 672,000</strong></div><div class="card kpi"><p>逾期应收款</p><strong class="red">¥ 96,000</strong></div></div><div class="two-col"><div class="card"><div class="section-head" style="padding:0 16px"><h2>合同台账</h2><button class="link">新建合同</button></div><div class="table-wrap"><table><thead><tr><th>合同编号</th><th>项目</th><th>动态总价</th><th>状态</th></tr></thead><tbody><tr><td>HT-2607-0001</td><td>星河科技办公楼改造</td><td>¥ 1,280,000</td><td><span class="badge green">已签署</span></td></tr><tr><td>HT-2607-0002</td><td>远航律所办公室修缮</td><td>¥ 320,000</td><td><span class="badge green">已签署</span></td></tr><tr><td>HT-2606-0012</td><td>南山咖啡旗舰店</td><td>¥ 486,000</td><td><span class="badge green">已签署</span></td></tr></tbody></table></div></div><div class="card"><div class="section-head" style="padding:0 16px"><h2>回款风险提醒</h2></div><div class="alert-row"><div><strong>远航律所首期款</strong><span class="sub">应收 ¥96,000 · 已逾期 8 天</span></div><span class="badge red">立即跟进</span></div><div class="alert-row"><div><strong>星河科技中期款</strong><span class="sub">应收 ¥384,000 · 计划 07-20</span></div><span class="badge orange">9 天后到期</span></div><div class="alert-row"><div><strong>南山咖啡质保金</strong><span class="sub">¥24,300 · 30 天后可催收</span></div><span class="badge blue">待提醒</span></div></div></div>`) }
function profit(){layout(`<div class="grid kpi-grid"><div class="card kpi"><p>动态合同收入</p><strong>¥ 2,086,000</strong><span class="sub">初始合同 + 已生效签证</span></div><div class="card kpi"><p>项目毛利</p><strong class="profit-positive">¥ 746,580</strong><span class="sub">毛利率 35.79%</span></div><div class="card kpi"><p>净现金流</p><strong>¥ 318,000</strong><span class="sub">累计已收 - 累计已付</span></div></div><div class="two-col"><div class="card meter"><h3>项目综合毛利率</h3><div class="number profit-positive">35.79%</div><div class="bar"><i style="width:71.58%"></i></div><span class="sub">目标毛利率：30%</span></div><div class="card meter"><h3>收款完成率</h3><div class="number">51.7%</div><div class="bar"><i style="width:51.7%;background:#2563eb"></i></div><span class="sub">已收 ¥1,078,000 / 动态收入 ¥2,086,000</span></div></div><div class="section-head"><h2>项目利润明细</h2><button class="secondary">导出报表</button></div><div class="card table-wrap"><table><thead><tr><th>项目</th><th>动态收入</th><th>采购支出</th><th>人工支出</th><th>毛利</th><th>毛利率</th><th>已收款</th><th>净现金流</th></tr></thead><tbody><tr><td class="project-name">星河科技办公楼改造</td><td>¥ 1,280,000</td><td>¥ 402,600</td><td>¥ 176,240</td><td class="profit-positive">¥ 701,160</td><td class="profit-positive">54.78%</td><td>¥ 640,000</td><td>¥ 228,000</td></tr><tr><td class="project-name">远航律所办公室修缮</td><td>¥ 320,000</td><td>¥ 124,820</td><td>¥ 46,300</td><td class="profit-positive">¥ 148,880</td><td class="profit-positive">46.53%</td><td>¥ 96,000</td><td>¥ 42,000</td></tr><tr><td class="project-name">南山咖啡旗舰店</td><td>¥ 486,000</td><td>¥ 259,900</td><td>¥ 76,100</td><td class="profit-positive">¥ 150,000</td><td class="profit-positive">30.86%</td><td>¥ 342,000</td><td>¥ 48,000</td></tr></tbody></table></div>`) }
function settings(){layout(`<div class="card" style="padding:20px"><h2 style="margin-top:0;font-size:16px">系统参数</h2><div class="form-grid"><div class="field"><label>赢单审批阈值（元）</label><input value="50000" type="number" /></div><div class="field"><label>默认质保金比例</label><input value="5" type="number" /></div><div class="field"><label>线索接入超时（天）</label><input value="7" type="number" /></div><div class="field"><label>工单处理中超时（小时）</label><input value="48" type="number" /></div><div class="field full"><label>法定节假日配置</label><textarea rows="3" placeholder="例如：2026-10-01, 2026-10-02"></textarea></div></div><div class="form-actions"><button class="primary" id="save-settings">保存设置</button></div></div>`);$('#save-settings').onclick=()=>toast('系统参数已保存')}
function openLeadModal(){openModal('新建线索',`<div class="form-grid"><div class="field full"><label>线索名称 *</label><input required name="name" placeholder="例如：XX 公司办公室改造" /></div><div class="field"><label>客户名称 *</label><input required name="customer" /></div><div class="field"><label>负责人 *</label><select name="owner"><option>陈晓</option><option>李敏</option></select></div><div class="field"><label>预计面积（㎡）</label><input name="area" type="number" /></div><div class="field"><label>预计预算（元）</label><input name="budget" type="number" /></div><div class="field full"><label>线索来源</label><select><option>客户转介绍</option><option>线上咨询</option><option>老客户复购</option><option>线下拜访</option></select></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">创建线索</button></div>`,form=>{const d=new FormData(form);state.leads.unshift({name:d.get('name'),customer:d.get('customer'),area:(d.get('area')||'—')+'㎡',budget:money(d.get('budget')||0),owner:d.get('owner'),stage:0,age:'接入第 0 天'});closeModal();leads();toast('线索已创建，已进入线索接入阶段')})}
function openWorkModal(){openModal('验收销账',`<div class="form-grid"><div class="field full"><label>验收结论 *</label><select name="result"><option value="pass">验收通过，销账</option><option value="return">验收不通过，退回处理</option></select></div><div class="field full"><label>销账照片 *</label><input name="photo" type="file" accept="image/*" required /></div><div class="field full"><label>验收备注</label><textarea name="note" rows="3" placeholder="填写验收情况"></textarea></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">提交验收</button></div>`,()=>{closeModal();toast('工单已销账，验收锁定状态将自动刷新')})}
function openModal(title,html,submit){$('#modal-title').textContent=title;const f=$('#modal-form');f.innerHTML=html;$('#modal').classList.remove('hidden');f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('button[type="submit"],button.primary:not([data-close])');if(button?.disabled)return;const label=button?.textContent;if(button){button.disabled=true;button.textContent='处理中…'}try{await submit(f)}finally{if(button){button.disabled=false;button.textContent=label}}};f.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal)}function closeModal(){$('#modal').classList.add('hidden')}
const views={dashboard,leads,projects,bom,workorders,labor,contracts,profit,settings};
views.dashboard=()=>layout('<div class="card empty">正在加载真实经营数据…</div>');
const titles={dashboard:'早上好，团光',leads:'线索跟进',projects:'项目管理',bom:'BOM 台账',workorders:'现场工单',labor:'人力日报',contracts:'合同与回款',profit:'利润看板',settings:'系统设置'};
function render(view){if(window.__appBooting){window.__bootView=view;return}state.view=view;$('#page-title').textContent=titles[view];$('#breadcrumb').textContent=view==='dashboard'?'工作台':'业务管理 / '+titles[view];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));views[view]();$('#new-action').textContent=view==='leads'?'＋ 新建线索':view==='workorders'?'＋ 拍照建单':'＋ 新建线索';}
document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>render(x.dataset.view));document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)render(go.dataset.go);if(e.target.matches('[data-close]'))closeModal()});$('#new-action').onclick=()=>state.view==='workorders'?openWorkModal():openLeadModal();$('#notify').onclick=()=>toast('提醒中心：6 条待办，其中 2 条需紧急处理');render('dashboard');

// 后端数据接入：页面通过 server.py 提供的 REST API 读写 SQLite。
const API_ORIGIN=window.API_ORIGIN||'https://zrylyjtbjhqffqggphad.supabase.co/functions/v1/project-api';
const apiCache=new Map(),apiInflight=new Map();let apiCacheGeneration=0;
function invalidateApiCache(){apiCacheGeneration++;apiCache.clear()}
async function api(path, options={}) {
  const method=String(options.method||'GET').toUpperCase(),cacheKey=path,cached=apiCache.get(cacheKey);
  if(method==='GET'&&cached&&cached.expires>Date.now())return cached.value;
  if(method==='GET'&&apiInflight.has(cacheKey))return apiInflight.get(cacheKey);
  const generation=apiCacheGeneration;
  const request=(async()=>{
    const token = await window.getAuthAccessToken?.();
    if (!token) throw new Error('请先登录');
    const response = await fetch(`${API_ORIGIN}${path}`, {
      ...options,
      headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`},
    });
    const payload = await response.json();
    if (!response.ok) throw new Error(payload.error || '请求失败');
    if(method==='GET'&&generation===apiCacheGeneration)apiCache.set(cacheKey,{value:payload,expires:Date.now()+15000});
    if(method!=='GET')invalidateApiCache();
    return payload;
  })();
  if(method==='GET')apiInflight.set(cacheKey,request);
  try{return await request}finally{if(method==='GET')apiInflight.delete(cacheKey)}
}
function formatLead(item) {
  const started = new Date(item.stage_since);
  const days = Math.max(0, Math.floor((Date.now() - started.getTime()) / 86400000));
  return {id:item.id,name:item.name,customer:item.customer,area:item.area ? `${item.area}㎡` : '—',budget:money(item.budget||0),owner:item.owner,stage:item.stage,age:`${stages[item.stage]}第 ${days} 天`};
}
async function refreshLeads() {
  const data = await api('/api/leads');
  state.leads = data.items.map(formatLead);
}
renderLeadRows = function() {
  const q=($('#lead-search')?.value||'').trim(); const f=$('#stage-filter')?.value||'';
  const rows=state.leads.filter(x=>(!q||x.name.includes(q)||x.customer.includes(q))&&(!f||stages[x.stage]===f));
  $('#lead-body').innerHTML=rows.map(x=>`<tr><td><span class="project-name">${x.name}</span></td><td>${x.customer}</td><td>${x.area}<span class="sub">${x.budget}</span></td><td>${stageHtml(x.stage)}</td><td>${x.owner}</td><td><span class="${x.age.includes('6')?'badge orange':''}">${x.age}</span></td><td><button class="action" data-advance="${x.id}">推进阶段</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无符合条件的线索</td></tr>';
  document.querySelectorAll('[data-advance]').forEach(button=>button.onclick=async()=>{
    try { await api(`/api/leads/${button.dataset.advance}/advance`, {method:'PATCH',body:'{}'}); await refreshLeads(); renderLeadRows(); toast('线索阶段已更新'); }
    catch(error) { toast(error.message); }
  });
};
const legacyLeadsView = views.leads;
views.leads = async function() {
  legacyLeadsView();
  try { await refreshLeads(); renderLeadRows(); } catch(error) { toast('后端未连接，请使用 server.py 启动系统'); }
};
openLeadModal = function() {
  openModal('新建线索',`<div class="form-grid"><div class="field full"><label>线索名称 *</label><input required name="name" placeholder="例如：XX 公司办公室改造" /></div><div class="field"><label>客户名称 *</label><input required name="customer" /></div><div class="field"><label>负责人 *</label><select name="owner"><option>陈晓</option><option>李敏</option></select></div><div class="field"><label>预计面积（㎡）</label><input name="area" type="number" /></div><div class="field"><label>预计预算（元）</label><input name="budget" type="number" /></div><div class="field full"><label>线索来源</label><select name="source"><option>客户转介绍</option><option>线上咨询</option><option>老客户复购</option><option>线下拜访</option></select></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">创建线索</button></div>`,async form=>{
    const data=Object.fromEntries(new FormData(form));
    try { await api('/api/leads',{method:'POST',body:JSON.stringify(data)}); closeModal(); await refreshLeads(); renderLeadRows(); toast('线索已保存到数据库'); }
    catch(error) { toast(error.message); }
  });
};
views.projects = async function() {
  layout('<div class="card empty">正在加载项目数据…</div>');
  try {
    const data=await api('/api/projects');
    layout(`<div class="card table-wrap"><table><thead><tr><th>项目编号</th><th>项目名称</th><th>业务负责人</th><th>项目经理</th><th>合同金额</th><th>进度</th><th>状态</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${x.code}</td><td><span class="project-name">${x.name}</span><span class="sub">BOM ${x.bom_version||'V0.1'}</span></td><td>${x.sales_owner||'—'}</td><td>${x.manager||'—'}</td><td>${money(x.contract_amount)}</td><td><div class="progress"><i style="width:${x.progress}%"></i></div><span class="sub">${x.progress}%</span></td><td><span class="badge ${x.status.includes('风险')?'red':x.status.includes('预警')?'orange':'green'}">${x.status}</span></td></tr>`).join('')}</tbody></table></div>`);
  } catch(error) { layout('<div class="card empty">后端未连接，请使用 server.py 启动系统。</div>'); }
};
views.workorders = async function() {
  layout('<div class="card empty">正在加载工单…</div>');
  try {
    const data=await api('/api/work-orders');
    layout(`<div class="toolbar"><div class="filters"><select><option>全部状态</option><option>待派发</option><option>处理中</option><option>待验收</option></select></div><button class="primary" id="add-work">＋ 拍照建单</button></div><div class="card table-wrap"><table><thead><tr><th>工单编号</th><th>问题描述</th><th>项目</th><th>责任人</th><th>状态</th><th>操作</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${x.code}</td><td><span class="project-name">${x.description}</span><span class="sub">${x.work_type}类</span></td><td>${x.project_name||'—'}</td><td>${x.assignee||'—'}</td><td><span class="badge ${x.status==='待验收'?'orange':x.status==='已销账'?'green':'blue'}">${x.status}</span></td><td>${x.status==='待验收'?`<button class="action" data-close-work="${x.id}">验收销账</button>`:'<button class="action">查看</button>'}</td></tr>`).join('')}</tbody></table></div>`);
    $('#add-work').onclick=()=>toast('一期可从项目详情创建并上传现场照片');
    document.querySelectorAll('[data-close-work]').forEach(button=>button.onclick=()=>openWorkModal(button.dataset.closeWork));
  } catch(error) { layout('<div class="card empty">后端未连接，请使用 server.py 启动系统。</div>'); }
};
openWorkModal = function(id) {
  openModal('验收销账',`<div class="form-grid"><div class="field full"><label>销账照片 *</label><input name="photo" type="file" accept="image/*" required /></div><div class="field full"><label>验收备注</label><textarea name="note" rows="3" placeholder="填写验收情况"></textarea></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">提交验收</button></div>`,async form=>{
    const photo=form.elements.photo.files[0];
    if(!photo) return toast('请上传销账照片');
    try { await api(`/api/work-orders/${id}/close`,{method:'PATCH',body:JSON.stringify({closure_photo:photo.name})}); closeModal(); views.workorders(); toast('工单已销账并写入操作日志'); }
    catch(error) { toast(error.message); }
  });
};
views.labor = async function() {
  layout('<div class="card empty">正在加载日报…</div>');
  try {
    const data=await api('/api/labor-reports');
    layout(`<div class="card table-wrap"><table><thead><tr><th>项目</th><th>日期</th><th>工种</th><th>出勤人数</th><th>工时</th><th>人工成本</th><th>状态</th><th>操作</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${x.project_name||'—'}</td><td>${x.report_date}</td><td>${x.trade}</td><td>${x.workers} 人</td><td>${x.hours} h</td><td>${money(x.cost)}</td><td><span class="badge ${x.status==='已审核'?'green':'orange'}">${x.status}</span></td><td>${x.status==='待审核'?`<button class="action" data-approve="${x.id}">审核通过</button>`:'<button class="action">查看</button>'}</td></tr>`).join('')}</tbody></table></div>`);
    document.querySelectorAll('[data-approve]').forEach(button=>button.onclick=async()=>{try{await api(`/api/labor-reports/${button.dataset.approve}/approve`,{method:'PATCH',body:'{}'});views.labor();toast('日报已审核，成本已计入利润口径')}catch(error){toast(error.message)}});
  } catch(error) { layout('<div class="card empty">后端未连接，请使用 server.py 启动系统。</div>'); }
};
