/* 线索与项目可视化看板。 */
(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const leadPeriodKey=(date,type)=>{const value=String(date||'').slice(0,10),year=value.slice(0,4),month=Number(value.slice(5,7)||1);if(type==='year')return year;if(type==='quarter')return `${year}-Q${Math.ceil(month/3)}`;return value.slice(0,7)};
  const periodOptions=(items,type)=>[...new Set(items.map(item=>leadPeriodKey(item.created_at,type)).filter(Boolean))].sort().reverse();
  const leadStatus=item=>item.status||'进行中';
  views.leads=async function(){
    layout('<div class="card empty">正在加载线索看板…</div>');
    try{
      await refreshLeads();
      const now=new Date(),currentMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
      layout(`<div class="toolbar"><div class="filters"><select id="lead-period-type"><option value="month">月度</option><option value="quarter">季度</option><option value="year">年度</option></select><select id="lead-period"></select><input id="lead-visual-search" placeholder="搜索客户或线索" /></div><button class="primary" id="add-lead">＋ 新建线索</button></div><div id="lead-visual"></div><div class="section-head"><h2>线索明细</h2></div><div class="card table-wrap"><table><thead><tr><th>创建时间</th><th>线索名称</th><th>客户</th><th>负责人</th><th>当前阶段</th><th>结果</th><th>操作</th></tr></thead><tbody id="lead-visual-body"></tbody></table></div>`);
      const type=$('#lead-period-type'),period=$('#lead-period'),search=$('#lead-visual-search');
      const leadItems=Array.isArray(state.leads)?state.leads:[];
      const resetPeriods=()=>{const values=periodOptions(leadItems,type.value);period.innerHTML=`<option value="">全部${type.value==='month'?'月份':type.value==='quarter'?'季度':'年度'}</option>${values.map(value=>`<option value="${value}" ${type.value==='month'&&value===currentMonth?'selected':''}>${value}</option>`).join('')}`;draw()};
      const draw=()=>{const query=search.value.trim().toLowerCase(),items=leadItems.filter(item=>(!period.value||leadPeriodKey(item.created_at,type.value)===period.value)&&(!query||`${item.name} ${item.customer}`.toLowerCase().includes(query))),won=items.filter(item=>leadStatus(item)==='已赢单').length,lost=items.filter(item=>leadStatus(item)==='未成交').length,talking=items.filter(item=>leadStatus(item)==='进行中').length,total=items.length,conversion=total?won/total*100:0,stageCounts=stages.map((name,index)=>({name,count:items.filter(item=>leadStatus(item)==='进行中'&&Number(item.stage)===index).length})),maxStage=Math.max(...stageCounts.map(x=>x.count),1);$('#lead-visual').innerHTML=`<div class="grid kpi-grid"><div class="card kpi"><p>客户线索</p><strong>${total}</strong><span class="sub">所选周期新增客户</span></div><div class="card kpi"><p>已经成交</p><strong>${won}</strong><span class="sub">成交率 ${conversion.toFixed(1)}%</span></div><div class="card kpi"><p>正在洽谈</p><strong>${talking}</strong></div><div class="card kpi"><p>未成交</p><strong>${lost}</strong></div></div><div class="visual-grid"><div class="card visual-panel"><div class="section-head"><h2>客户转化</h2><strong>${conversion.toFixed(1)}%</strong></div><div class="donut" style="--value:${conversion}"><div><strong>${won}</strong><span>成交客户</span></div></div><div class="visual-legend"><span><i class="won"></i>成交 ${won}</span><span><i class="talking"></i>在谈 ${talking}</span><span><i class="lost"></i>未成交 ${lost}</span></div></div><div class="card visual-panel"><div class="section-head"><h2>在谈客户阶段分布</h2></div><div class="stage-bars">${stageCounts.map(stage=>`<div class="stage-bar"><span>${stage.name}</span><div><i style="width:${stage.count/maxStage*100}%"></i></div><strong>${stage.count}</strong></div>`).join('')}</div></div></div>`;$('#lead-visual-body').innerHTML=items.map(item=>`<tr><td>${String(item.created_at||'').slice(0,10)}</td><td><strong>${esc(item.name)}</strong><span class="sub">${item.area||'—'} · ${item.budget||money(0)}</span></td><td>${esc(item.customer)}</td><td>${esc(item.owner)}</td><td>${leadStatus(item)==='进行中'?stageHtml(item.stage):'—'}</td><td><span class="badge ${statusClass(leadStatus(item))}">${leadStatus(item)}</span></td><td>${leadActions(item)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">该周期暂无客户线索</td></tr>';bindLeadActions()};
      type.onchange=resetPeriods;period.onchange=draw;search.oninput=draw;$('#add-lead').onclick=openLeadModal;resetPeriods();
    }catch(error){layout(`<div class="card empty">线索看板加载失败：${error.message}</div>`)}
  };
  views.projects=async function(){
    layout('<div class="card empty">正在加载项目看板…</div>');
    try{
      await loadProjects();const details=await Promise.all(appState.projects.map(project=>api(`/api/projects/${project.id}/detail`).then(detail=>({project,...detail})))),today=new Date().toISOString().slice(0,10),active=details.filter(x=>!['已完工','已完成'].includes(x.project.status)),delayed=details.filter(x=>x.milestones.some(m=>Number(m.progress)<100&&m.planned_date&&m.planned_date<today)),warning=details.filter(x=>!delayed.includes(x)&&x.milestones.some(m=>Number(m.progress)<100&&m.planned_date&&Math.ceil((new Date(m.planned_date)-new Date())/86400000)<=7)),average=active.length?active.reduce((sum,x)=>sum+Number(x.project.progress||0),0)/active.length:0;
      layout(`<div class="grid kpi-grid"><div class="card kpi"><p>全部项目</p><strong>${details.length}</strong></div><div class="card kpi"><p>正在施工</p><strong>${active.length}</strong></div><div class="card kpi"><p>平均进度</p><strong>${average.toFixed(0)}%</strong></div><div class="card kpi"><p>延期预警</p><strong class="red">${delayed.length}</strong><span class="sub">7天内到期 ${warning.length}</span></div></div><div class="section-head"><h2>项目关键阶段与工期</h2></div><div class="project-visual-list">${details.map(data=>{const project=data.project,milestones=data.milestones||[],current=milestones.find(m=>Number(m.progress)<100),late=milestones.filter(m=>Number(m.progress)<100&&m.planned_date&&m.planned_date<today),near=!late.length&&milestones.filter(m=>Number(m.progress)<100&&m.planned_date&&Math.ceil((new Date(m.planned_date)-new Date())/86400000)<=7),endDate=data.contract?.end_date||milestones.map(m=>m.planned_date).filter(Boolean).sort().pop(),days=endDate?Math.ceil((new Date(endDate)-new Date())/86400000):null,alert=late.length?'已延期':near.length?'即将到期':'正常';return `<div class="card project-visual-card"><div class="project-visual-head"><div><button class="action project-title" data-project="${project.id}">${esc(project.code)} · ${esc(project.name)}</button><span class="sub">当前关键阶段：${esc(current?.name||'全部节点已完成')}　计划完工：${endDate||'未设置'}</span></div><span class="badge ${late.length?'red':near.length?'orange':'green'}">${alert}${days===null?'':days<0?` ${Math.abs(days)}天`:` ${days}天`}</span></div><div class="project-progress"><div><i style="width:${Number(project.progress||0)}%"></i></div><strong>${Number(project.progress||0)}%</strong></div><div class="milestone-line">${milestones.map(m=>`<div class="milestone-point ${Number(m.progress)>=100?'done':m===current?'current':''}"><i></i><span>${esc(m.name)}</span><small>${m.planned_date||'待定'}</small></div>`).join('')||'<span class="sub">尚未设置施工关键节点</span>'}</div>${late.length?`<div class="project-warning">延期节点：${late.map(m=>`${esc(m.name)}（${m.planned_date}）`).join('、')}</div>`:''}</div>`}).join('')||'<div class="card empty">暂无项目</div>'}</div>`);document.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>projectDetail(button.dataset.project));
    }catch(error){layout(`<div class="card empty">项目看板加载失败：${error.message}</div>`)}
  };
})();
