/* 业务流增强：线索 → 项目 → 合同 → 施工计划 → 项目内 BOM / 工单。 */
const appState={projects:[],selectedProjectId:null};
const lossReasons=['价格超预算','败给竞品','工期无法满足','设计方案未中标','项目搁置','付款条件未达成','其他'];
const statusClass=status=>status.includes('风险')||status.includes('逾期')?'red':status.includes('预警')||status.includes('待')?'orange':status.includes('已')||status.includes('施工')?'green':'blue';
formatLead=function(item){const started=new Date(item.stage_since),days=Math.max(0,Math.floor((Date.now()-started.getTime())/86400000));return {id:item.id,name:item.name,customer:item.customer,area:item.area?`${item.area}㎡`:'—',budget:money(item.budget||0),owner:item.owner,stage:item.stage,age:`${stages[item.stage]}第 ${days} 天`,status:item.status,lost_reason:item.lost_reason,lost_note:item.lost_note}};
const selectProjects=(selected='')=>`<select name="project_id" required><option value="">请选择项目</option>${appState.projects.map(p=>`<option value="${p.id}" ${String(p.id)===String(selected)?'selected':''}>${p.code} · ${p.name}</option>`).join('')}</select>`;
async function loadProjects(){appState.projects=(await api('/api/projects')).items;return appState.projects}
function setHeader(view){state.view=view;$('#page-title').textContent=titles[view]||'项目详情';$('#breadcrumb').textContent=view==='dashboard'?'工作台':'业务管理 / '+(titles[view]||'项目详情');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const button=$('#new-action');button.classList.toggle('hidden',view!=='leads');button.textContent='＋ 新建线索';button.onclick=openLeadModal}
render=function(view){setHeader(view);views[view]()};

views.leads=async function(){
  layout(`<div class="toolbar"><div class="filters"><input class="input" id="lead-search" placeholder="搜索线索名称、客户" /><select id="stage-filter"><option value="">全部阶段</option>${stages.map(s=>`<option>${s}</option>`).join('')}</select><select id="lead-status"><option value="">全部状态</option><option value="进行中">进行中</option><option value="已赢单">已赢单</option><option value="未成交">未成交</option></select></div><button class="primary" id="add-lead">＋ 新建线索</button></div><div class="card table-wrap"><table><thead><tr><th>线索名称</th><th>客户</th><th>负责人</th><th>当前阶段</th><th>结果</th><th>操作</th></tr></thead><tbody id="lead-body"></tbody></table></div>`);
  $('#add-lead').onclick=openLeadModal;['lead-search','stage-filter','lead-status'].forEach(id=>$('#'+id).oninput=renderEnterpriseLeads);try{await refreshLeads();renderEnterpriseLeads()}catch(error){toast('后端未连接')}
};
function renderEnterpriseLeads(){const q=$('#lead-search').value.trim(),stage=$('#stage-filter').value,status=$('#lead-status').value;const rows=state.leads.filter(x=>(!q||x.name.includes(q)||x.customer.includes(q))&&(!stage||stages[x.stage]===stage)&&(!status||x.status===status));$('#lead-body').innerHTML=rows.map(x=>`<tr><td><span class="project-name">${x.name}</span><span class="sub">${x.area} · ${x.budget}</span></td><td>${x.customer}</td><td>${x.owner}</td><td>${x.status==='进行中'?stageHtml(x.stage):'—'}</td><td>${x.status==='未成交'?`<span class="badge red">未成交：${x.lost_reason||'—'}</span>`:x.status==='已赢单'?'<span class="badge green">已赢单</span>':'<span class="badge blue">跟进中</span>'}</td><td>${x.status==='进行中'?`<button class="action" data-advance="${x.id}">推进</button> <button class="action" data-win="${x.id}">赢单</button> <button class="action" data-lose="${x.id}">未成交</button>`:'<button class="action" data-show-lead="${x.id}">查看</button>'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无符合条件的线索</td></tr>';
  document.querySelectorAll('[data-advance]').forEach(b=>b.onclick=async()=>{try{await api(`/api/leads/${b.dataset.advance}/advance`,{method:'PATCH',body:'{}'});await refreshLeads();renderEnterpriseLeads();toast('已推进至下一阶段')}catch(e){toast(e.message)}});
  document.querySelectorAll('[data-lose]').forEach(b=>b.onclick=()=>openLoseModal(b.dataset.lose));document.querySelectorAll('[data-win]').forEach(b=>b.onclick=()=>openWinModal(b.dataset.win));
}
openLeadModal=function(){openModal('新建线索',`<div class="form-grid"><div class="field full"><label>线索名称 *</label><input name="name" required /></div><div class="field"><label>客户名称 *</label><input name="customer" required /></div><div class="field"><label>负责人 *</label><input name="owner" required placeholder="可自行输入负责人姓名" /></div><div class="field"><label>预计面积（㎡）</label><input name="area" type="number" /></div><div class="field"><label>预计预算（元）</label><input name="budget" type="number" /></div><div class="field full"><label>来源</label><input name="source" placeholder="客户转介绍、线上咨询等" /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">保存线索</button></div>`,async form=>{try{await api('/api/leads',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});closeModal();views.leads();toast('线索已创建')}catch(e){toast(e.message)}})};
function openLoseModal(id){openModal('登记未成交原因',`<div class="form-grid"><div class="field full"><label>未成交原因 *</label><select name="lost_reason">${lossReasons.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field full"><label>补充说明</label><textarea name="lost_note" rows="3"></textarea></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">确认未成交</button></div>`,async form=>{try{await api(`/api/leads/${id}/lose`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(form)))});closeModal();await refreshLeads();renderMonthlyLeads();toast('已记录未成交原因')}catch(e){toast(`标记未成交失败：${e.message}`)}})}
function openWinModal(id){openModal('确认赢单并立项',`<div class="form-grid"><div class="field full"><label>项目经理</label><input name="manager" placeholder="请输入项目经理姓名" /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">赢单并创建项目</button></div>`,async form=>{try{await api(`/api/leads/${id}/win`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(form)))});closeModal();toast('已赢单，项目与 BOM 草稿已创建');render('projects')}catch(e){toast(e.message)}})}

views.projects=async function(){layout('<div class="card empty">正在加载项目…</div>');try{await loadProjects();layout(`<div class="notice">项目必须先建立合同，才能安排施工计划和控制进度。点击项目可进入项目内管理。</div><div class="card table-wrap"><table><thead><tr><th>项目编号</th><th>项目名称</th><th>合同状态</th><th>施工进度</th><th>状态</th><th>操作</th></tr></thead><tbody>${appState.projects.map(p=>`<tr><td>${p.code}</td><td><span class="project-name">${p.name}</span><span class="sub">项目经理：${p.manager||'待分配'}</span></td><td>${p.contract_amount?money(p.contract_amount):'<span class="badge orange">待建合同</span>'}</td><td><div class="progress"><i style="width:${p.progress}%"></i></div><span class="sub">${p.progress}%</span></td><td><span class="badge ${statusClass(p.status)}">${p.status}</span></td><td><button class="action" data-project="${p.id}">进入项目</button></td></tr>`).join('')}</tbody></table></div>`);document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>projectDetail(b.dataset.project))}catch(e){layout('<div class="card empty">后端未连接</div>')}};
async function projectDetail(id){appState.selectedProjectId=id;setHeader('projects');layout('<div class="card empty">正在加载项目详情…</div>');try{const data=await api(`/api/projects/${id}/detail`),p=data.project,c=data.contract;layout(`<div class="toolbar"><button class="secondary" id="back-projects">← 返回项目列表</button><div>${c?`<button class="secondary" id="open-bom">BOM 与发票</button> <button class="primary" id="open-work">项目内新建问题</button>`:''}</div></div><div class="card bom-summary"><div><h3>${p.code} · ${p.name}</h3><p>业务：${p.sales_owner||'—'}　项目经理：${p.manager||'—'}　未闭环问题：${data.open_work_orders} 项</p></div><span class="badge ${statusClass(p.status)}">${p.status}</span></div>${!c?`<div class="card empty"><strong>尚未建立合同</strong><p>施工计划和进度控制将在合同签署后开放。</p><button class="primary" id="create-contract">建立合同</button></div>`:`<div class="grid kpi-grid" style="margin-top:18px"><div class="card kpi"><p>合同编号</p><strong style="font-size:18px">${c.code}</strong><span class="sub">${c.party_a}</span></div><div class="card kpi"><p>合同金额</p><strong>${money(c.amount)}</strong></div><div class="card kpi"><p>约定竣工日</p><strong style="font-size:18px">${c.completion_date||'未填写'}</strong></div></div><div class="section-head"><h2>施工关键节点</h2><button class="primary" id="add-milestone">＋ 新增关键节点</button></div><div class="card table-wrap"><table><thead><tr><th>关键节点</th><th>计划日期</th><th>状态</th><th>节点进度</th><th>调整</th></tr></thead><tbody>${data.milestones.map(m=>`<tr><td class="project-name">${m.name}</td><td>${m.planned_date}</td><td><span class="badge ${statusClass(m.status)}">${m.status}</span></td><td><div class="progress"><i style="width:${m.progress}%"></i></div><span class="sub">${m.progress}%</span></td><td><input data-milestone="${m.id}" type="range" min="0" max="100" value="${m.progress}" /><button class="action" data-save-milestone="${m.id}">保存</button></td></tr>`).join('')}</tbody></table></div>`}`);$('#back-projects').onclick=()=>render('projects');if(!c){$('#create-contract').onclick=()=>openContractModal(p.id);return}$('#open-bom').onclick=()=>openBom(p.id);$('#open-work').onclick=()=>openProjectWork(p.id);$('#add-milestone').onclick=()=>openMilestoneModal(p.id);document.querySelectorAll('[data-save-milestone]').forEach(b=>b.onclick=async()=>{const input=$(`[data-milestone="${b.dataset.saveMilestone}"]`);await api(`/api/milestones/${b.dataset.saveMilestone}/progress`,{method:'PATCH',body:JSON.stringify({progress:input.value})});toast('节点进度已更新');projectDetail(id)})}catch(e){layout(`<div class="card empty">${e.message}</div>`)}}

views.contracts=async function(){await loadProjects();const data=await api('/api/contracts');layout(`<div class="toolbar"><div><h2 style="margin:0;font-size:16px">合同管理</h2><span class="sub">合同签署后才可制定施工计划</span></div><button class="primary" id="new-contract">＋ 新建合同</button></div><div class="card table-wrap"><table><thead><tr><th>合同编号</th><th>项目</th><th>甲方</th><th>金额</th><th>竣工日期</th><th>状态</th></tr></thead><tbody>${data.items.map(c=>`<tr><td>${c.code}</td><td>${c.project_code} · ${c.project_name}</td><td>${c.party_a}</td><td>${money(c.amount)}</td><td>${c.completion_date||'—'}</td><td><span class="badge ${statusClass(c.status)}">${c.status}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无合同</td></tr>'}</tbody></table></div>`);$('#new-contract').onclick=()=>openContractModal()};
function openContractModal(projectId=''){openModal('新建合同',`<div class="form-grid"><div class="field full"><label>关联项目 *</label>${selectProjects(projectId)}</div><div class="field"><label>甲方 *</label><input name="party_a" required /></div><div class="field"><label>合同金额 *</label><input name="amount" type="number" required /></div><div class="field"><label>签署日期</label><input name="signed_date" type="date" /></div><div class="field"><label>约定竣工日期</label><input name="completion_date" type="date" /></div><div class="field full"><label>合同文件（文件名）</label><input name="file_name" placeholder="例如：装修合同.pdf" /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">保存合同</button></div>`,async form=>{try{await api('/api/contracts',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});closeModal();toast('合同已建立，现在可安排施工计划');projectId?projectDetail(projectId):render('contracts')}catch(e){toast(e.message)}})}

function openBom(projectId){appState.selectedProjectId=projectId;setHeader('bom');views.bom()}
views.bom=async function(){await loadProjects();const id=appState.selectedProjectId||appState.projects[0]?.id;if(!id)return layout('<div class="card empty">请先创建项目</div>');appState.selectedProjectId=id;const [bom,invoices]=await Promise.all([api(`/api/bom-items?project_id=${id}`),api(`/api/invoices?project_id=${id}`)]);const total=bom.items.reduce((sum,x)=>sum+Number(x.subtotal),0);layout(`<div class="toolbar"><button class="secondary" id="back-detail">← 返回项目</button><div class="filters"><select id="bom-project">${appState.projects.map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${p.code} · ${p.name}</option>`).join('')}</select><button class="primary" id="add-material">＋ 新增材料</button></div></div><div class="grid kpi-grid"><div class="card kpi"><p>BOM 材料预估</p><strong>${money(total)}</strong></div><div class="card kpi"><p>已录入材料</p><strong>${bom.items.length} 项</strong></div><div class="card kpi"><p>材料发票金额</p><strong>${money(invoices.items.filter(x=>x.invoice_type==='材料').reduce((s,x)=>s+Number(x.amount),0))}</strong></div></div><div class="card table-wrap"><table><thead><tr><th>材料编码</th><th>材料 / 规格</th><th>设计用量</th><th>损耗</th><th>采购数量</th><th>单价</th><th>预估小计</th></tr></thead><tbody>${bom.items.map(x=>`<tr><td>${x.material_code}</td><td><span class="project-name">${x.material_name}</span><span class="sub">${x.specification||'—'} / ${x.unit}</span></td><td>${x.design_quantity}</td><td>${x.loss_rate}%</td><td>${x.purchase_quantity}</td><td>${money(x.unit_price)}</td><td>${money(x.subtotal)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无材料，请新增</td></tr>'}</tbody></table></div><div class="section-head"><h2>材料与人工发票</h2><button class="primary" id="add-invoice">＋ 录入发票</button></div><div class="card table-wrap"><table><thead><tr><th>类型</th><th>发票号码</th><th>关联材料</th><th>金额</th><th>附件</th></tr></thead><tbody>${invoices.items.map(x=>`<tr><td>${x.invoice_type}</td><td>${x.invoice_number}</td><td>${x.material_name||'—'}</td><td>${money(x.amount)}</td><td>${x.file_name||'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">暂无发票</td></tr>'}</tbody></table></div>`);$('#back-detail').onclick=()=>projectDetail(id);$('#bom-project').onchange=e=>openBom(e.target.value);$('#add-material').onclick=()=>openMaterialModal(id);$('#add-invoice').onclick=()=>openInvoiceModal(id,bom.items)};
function openMaterialModal(projectId){openModal('新增 BOM 材料',`<div class="form-grid"><div class="field"><label>材料编码 *</label><input name="material_code" required /></div><div class="field"><label>材料名称 *</label><input name="material_name" required /></div><div class="field"><label>规格</label><input name="specification" /></div><div class="field"><label>单位 *</label><input name="unit" required placeholder="张、㎡、套" /></div><div class="field"><label>设计用量 *</label><input name="design_quantity" type="number" required /></div><div class="field"><label>损耗率（%）</label><input name="loss_rate" type="number" value="0" /></div><div class="field full"><label>含税单价 *</label><input name="unit_price" type="number" required /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">新增材料</button></div>`,async form=>{const data=Object.fromEntries(new FormData(form));data.project_id=projectId;try{await api('/api/bom-items',{method:'POST',body:JSON.stringify(data)});closeModal();openBom(projectId);toast('材料已加入该项目 BOM')}catch(e){toast(e.message)}})}
function openInvoiceModal(projectId,items){openModal('录入材料/人工发票',`<div class="form-grid"><div class="field"><label>费用类型 *</label><select name="invoice_type"><option>材料</option><option>人工</option></select></div><div class="field"><label>关联材料</label><select name="bom_item_id"><option value="">不关联材料</option>${items.map(x=>`<option value="${x.id}">${x.material_name}</option>`).join('')}</select></div><div class="field"><label>发票号码 *</label><input name="invoice_number" required /></div><div class="field"><label>发票金额 *</label><input name="amount" type="number" required /></div><div class="field full"><label>发票附件（文件名）</label><input name="file_name" /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">保存发票</button></div>`,async form=>{const data=Object.fromEntries(new FormData(form));data.project_id=projectId;try{await api('/api/invoices',{method:'POST',body:JSON.stringify(data)});closeModal();openBom(projectId);toast('发票已录入')}catch(e){toast(e.message)}})}

function openMilestoneModal(projectId){openModal('新增施工关键节点',`<div class="form-grid"><div class="field full"><label>节点名称 *</label><input name="name" required placeholder="例如：隐蔽工程验收" /></div><div class="field full"><label>计划日期 *</label><input name="planned_date" type="date" required /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">新增节点</button></div>`,async form=>{const data=Object.fromEntries(new FormData(form));data.project_id=projectId;try{await api('/api/milestones',{method:'POST',body:JSON.stringify(data)});closeModal();projectDetail(projectId);toast('施工节点已新增')}catch(e){toast(e.message)}})}
function openProjectWork(projectId){openModal('项目内新建问题工单',`<div class="form-grid"><div class="field full"><label>问题描述 *</label><textarea name="description" rows="3" required></textarea></div><div class="field"><label>工单类型 *</label><select name="work_type"><option>整改</option><option>一般</option></select></div><div class="field"><label>责任人 *</label><input name="assignee" required /></div><div class="field"><label>要求完成时间</label><input name="due_at" type="datetime-local" /></div><div class="field"><label>现场图片（文件名）</label><input name="photo_name" placeholder="现场照片.jpg" /></div></div><div class="form-actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">创建问题工单</button></div>`,async form=>{const data=Object.fromEntries(new FormData(form));data.project_id=projectId;try{await api('/api/work-orders',{method:'POST',body:JSON.stringify(data)});closeModal();projectDetail(projectId);toast('项目问题工单已创建')}catch(e){toast(e.message)}})}
views.workorders=function(){layout('<div class="card empty"><strong>现场工单改为项目内管理</strong><p>请进入“项目管理”选择项目后，点击“项目内新建问题”。这样每条问题和现场图片均归属对应项目。</p><button class="primary" id="go-projects">进入项目管理</button></div>');$('#go-projects').onclick=()=>render('projects')};
render('dashboard');
